#!/bin/bash
# this a script to create/stop/status/start linux service
# by: chaoshen
# date: 2022-10-20

service_name='router-ip-watcher'

function usage() {
  echo "Usage: $0 create | stop | status | start"
  exit 1
}

# check have param
if [ $# -lt 1 ];then
  usage
fi

# check param length is not 1
if [ $# -ne 1 ];then
  usage
fi

# check param is create
if [ "$1" == "create" ];then
  python -c "from router_ip_watcher.utils import linux;linux.LinuxService('$service_name', 'cs-router-run-router-ip-watcher').create_service_file()"
  systemctl status $service_name
elif [ "$1" == "stop" ]; then
  systemctl disable $service_name
  systemctl stop $service_name
elif [ "$1" == "status" ]; then
  systemctl status $service_name
elif [ "$1" == "start" ]; then
  systemctl enable $service_name
  systemctl start $service_name
  systemctl status $service_name
else
  usage
fi
